### ISSUE TITLE
No vehicle in garage

### ISSUE THREAD

**Issue by HezimX** [HumanTree92/esx_advancedgarage#113]
Dosnt work for me with the newest esx_vehicleshop mabee have somthing with the fix sql the newest esx_vehicleshop uses
`owner` varchar(40) NOT NULL,
And if i use advancedgarage fix then i cant sell owned vehicles i get error ssying you dont owne that vehicle.
`owner` varchar(22) NOT NULL,

**Comment by ResqDiver1317** [comment]
Thanks to some stuff updating and some stuff not, I ended up just looking at all the SQLs and seeing what was missing from my DB structure to make sure all the tables needed were there. I found that some of the SQLs provided with resources did not have the tables needed and just trying to import the SQLs from others didn't work due to some stuff already existing so I just found what was missing and fixed my DB manually. It was a pain, but it got stuff working.

**Comment by HumanTree92** [comment]
Fixed in b766ddadab2922ecc62b3799e61d6f0ded8f5414
