### ISSUE TITLE
Trigger dont exist

### ISSUE THREAD

**Issue by kekev2001** [HumanTree92/esx_advancedgarage#132]
es_extended: TriggerServerCallback => [esx_advancedgarage:getOwnedCars] does not exist

I have not the Latest Esx the reason is that is new version is a litte buggy

and thiss error
Error loading script server/main.lua in resource esx_advancedgarage: @esx_advancedgarage/server/main.lua:26: attempt to call a nil value (field 'RegisterCommand')

**Comment by superq9** [comment]
I am getting the same error where it says es_extended: TriggerServerCallback => [esx_advancedgarage:getOwnedCars] does not exist

**Comment by HumanTree92** [comment]
Well since the updates that i am applying are for the latest ESX and the errors yall are receiving is b/c you have not updated to the latest ESX then there is no issues at all. 
These are your options: 
A. Update to the latest ESX
B. Edit the code to not use xPlayer.identifier
C. Download an older version of my code. [RIGHT HERE](https://github.com/HumanTree92/esx_advancedgarage/tree/535cb2b40bbce6e6ad94ad651f32a3e12f9e2aa3)

However do Note: That you will be missing out on a lot of updates & things might get broken. If so then your only resort is to update to the latest ESX.

**Comment by superq9** [comment]
Thanks
