### ISSUE TITLE
I can park my car but can no longer park it

### ISSUE THREAD

**Issue by TheAimOnPoint** [HumanTree92/esx_advancedgarage#152]
**Describe the bug | A Clear & Concise Description of Bug**

I can park my car but can no longer park it
https://prnt.sc/sozog0

**Questions**
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using Essentialmode?: No
Are you using the Latest es_extended?: Yes
Are you using OneSync?: No
Linux Server

**Comment by HumanTree92** [comment]
Send picture of ur owned_vehicle structure from ur database

**Comment by TheAimOnPoint** [comment]
https://prnt.sc/sp9zvp here i have used First the SQL from Vehicleshop and then from your script!

**Comment by TheAimOnPoint** [comment]
> Send picture of ur owned_vehicle structure from ur database
https://prnt.sc/sp9zvp here i have used First the SQL from Vehicleshop and then from your script!

**Comment by HumanTree92** [comment]
You must have a hard time following directions.

1. You didn't read through the Download & Installation b/c on 3. It says import the esx_vehicleshop_fix.sql into your database if using with esx_vehicleshop or edit your Database & change your job to NOT NULL & DEFAULT civ
2. You lied about reading the Wiki b/c you sure as hell didn't as your problem is fixed in there.
3. You lied about looking through the Closed Topics as this has been answered many times in closed Topics. 

You will now be Blocked.
