### ISSUE TITLE
Impound

### ISSUE THREAD

**Issue by kagesamo** [HumanTree92/esx_advancedgarage#182]
**Describe the Bug | A Clear & Concise Description of Bug**

Hello. 
My problem is when I try to use the impound to get back a vehicle, which has been destroyed or lost, it doesn't work. Shows the message in the first image.
The only way I managed to get the vehicle from impound was despawning it (In my case I used the "/dv" command).
Is it supposed to work like that?
Sincerely and best regards

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: Yes
Have you looked through the Wiki?: Yes
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): v1 Finale
Are you using Essentialmode?: No
Are you using ExtendedMode?: No
Are you using OneSync?: Not yet
Linux or Windows?: Windows at the time
![Capturar](https://user-images.githubusercontent.com/28874080/93724313-da5a2700-fb9d-11ea-8cc3-0f715b99a347.JPG)
![Capturar2](https://user-images.githubusercontent.com/28874080/93724340-12fa0080-fb9e-11ea-9624-da32f5bdca59.JPG)
![Capturar3](https://user-images.githubusercontent.com/28874080/93724341-13929700-fb9e-11ea-9362-da724c46a397.JPG)

**Comment by bluethunder88** [comment]
same issue i have a clue but unsure at this point and im using es_extended not v1 Finale
![Screenshot (10)](https://user-images.githubusercontent.com/71801598/94092400-aaeb2a80-fde8-11ea-9fa5-a813bece954d.png)

**Comment by HumanTree92** [comment]
This is because technically the vehicle still exists in the game. The new system uses [this Native](https://runtime.fivem.net/doc/natives/?_0x7239B21A38F536BA) which checks to see if an entity still exists in the game world. However i see what you mean but there isn't a way to fix it. What i suggest if a players vehicle blows up Realistically they should call the Police or Mechanic so they can remove the vehicle. Now if they crash the vehicle into the water don't know what to tell ya. 

You can probably use a vehicle cleanup script but this isn't an issue with this script & something i can't fix.
