### ISSUE TITLE
Will Garage intirior be added for Private Garages??

### ISSUE THREAD

**Issue by navin-hariharan** [HumanTree92/esx_advancedgarage#193]

**Comment by HumanTree92** [comment]
Nope never. I prefer to not use instances. As for interiors i prefer MLOs. I myself wouldn't mind Garage Interiors but for each property that would be a lot. You would need to setup a garage interior for every location. Or use a Vehicle Teleporter. I wouldn't recommend Vehicle Teleports due to if a player pulls a very large vehicle into a garage interior it could damage the vehicle.
