### ISSUE TITLE
Random Color When Take Out The Car From Impound

### ISSUE THREAD

**Issue by gerung** [HumanTree92/esx_advancedgarage#206]
**Describe the Bug | A Clear & Concise Description of Bug**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: No
Have you looked through the Closed Topics?: No
Have you looked through the Wiki?: No
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): No
Are you using Essentialmode?: No
Are you using ExtendedMode?: Yes
Are you using OneSync?: Yes
Linux or Windows?: Windows

I have a issue, when i take the car on the impound, the car color changes / random?

Thanks

**Comment by HumanTree92** [comment]
If you can show video proof of this happening that would be great. I have not had this issue at all.

**Comment by gerung** [comment]
The issue comes when you buy a new vehicle on dealer and tried to clear vehicle using F8 /dv or something, you can check video below
https://streamable.com/opt9m9

Base on video, i installed esx_advancedvehicle, you can see when i open shop menu i have another issue
`NETWORK_GET_NETWORK_ID_FROM_ENTITY: no net object for entity`
Thanks

**Comment by HumanTree92** [comment]
Honestly your pretty dumb. Here is the problem. When you purchase a vehicle it picks a random color for the vehicle. You DVed the vehicle instead of taking it to the garage to put it away. When you first purchase a vehicle it only saves the Model and Plate in the vehicle column. You must store your vehicle in the garage for it to fully save. Its why its best when you purchase a vehicle and make modifications you go back to the garage and store it so it saves.
