### ISSUE TITLE
No Vehicles in Garage

### ISSUE THREAD

**Issue by BoutProduction** [HumanTree92/esx_advancedgarage#48]
I have the problem that the vehicles you buy are not displayed in the garage ...

EDIT: I've already tried using your version of the "owned_vehicles" table, but as soon as I use it, I can not buy vehicles anymore

**Comment by HumanTree92** [comment]
[Check the Wiki](https://github.com/HumanTree92/esx_advancedgarage/wiki)

**Comment by BoutProduction** [comment]
Hello,
I've managed to park cars, but planes and boats are still not displayed

I changed that in the code to make it work again
this:
```
ESX.RegisterServerCallback('esx_advancedgarage:getOwnedCars', function(source, cb)
	local ownedCars = {}
	
	if Config.DontShowPoundCarsInGarage == true then
		MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND Type = @Type AND job = @job AND stored = @stored', {
			['@owner']  = GetPlayerIdentifiers(source)[1],
			['@Type']   = 'car',
			['@job']    = '',
			['@stored'] = true
		}, function(data)
			for _,v in pairs(data) do
				local vehicle = json.decode(v.vehicle)
				table.insert(ownedCars, {vehicle = vehicle, stored = v.stored, plate = v.plate})
			end
			cb(ownedCars)
		end)
	else
		MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND Type = @Type AND job = @job', {
			['@owner']  = GetPlayerIdentifiers(source)[1],
			['@Type']   = 'car',
			['@job']    = ''
		}, function(data)
			for _,v in pairs(data) do
				local vehicle = json.decode(v.vehicle)
				table.insert(ownedCars, {vehicle = vehicle, stored = v.stored, plate = v.plate})
			end
			cb(ownedCars)
		end)
	end
end)
```

to
```
ESX.RegisterServerCallback('esx_advancedgarage:getOwnedCars', function(source, cb)
	local ownedCars = {}
	
	if Config.DontShowPoundCarsInGarage == true then
		MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND Type = @Type AND job IS NULL AND stored = @stored', {
			['@owner']  = GetPlayerIdentifiers(source)[1],
			['@Type']   = 'car',
			['@stored'] = true
		}, function(data)
			for _,v in pairs(data) do
				local vehicle = json.decode(v.vehicle)
				table.insert(ownedCars, {vehicle = vehicle, stored = v.stored, plate = v.plate})
			end
			cb(ownedCars)
		end)
	else
		MySQL.Async.fetchAll('SELECT * FROM owned_vehicles WHERE owner = @owner AND Type = @Type AND job IS NULL', {
			['@owner']  = GetPlayerIdentifiers(source)[1],
			['@Type']   = 'car',
		}, function(data)
			for _,v in pairs(data) do
				local vehicle = json.decode(v.vehicle)
				table.insert(ownedCars, {vehicle = vehicle, stored = v.stored, plate = v.plate})
			end
			cb(ownedCars)
		end)
	end
end)
```

**Comment by Ghustavh97** [comment]
No need to change anything in the server/main.lua file since the script is looking for stored vehicles with **empty strings** as the type, change owned_vehicles job column default to empty string like this.

(https://user-images.githubusercontent.com/20132952/60928531-11e8f600-a2ae-11e9-9eff-dcb99ff6d710.png)

All vehicle storage should work now.

If you are using HeidiSQL do not type "" or '' when setting the default to an **empty string**, just leave the field empty and click ok it should do it for you.

DB Queries.

-- If the table does not exist yet.

CREATE TABLE IF NOT EXISTS `owned_vehicles` (
	`owner` varchar(22) NOT NULL,
	`plate` varchar(12) NOT NULL,
	`vehicle` longtext,
	`type` VARCHAR(20) NOT NULL DEFAULT 'car',
	`job` VARCHAR(20) NOT NULL DEFAULT '',
	`stored` TINYINT(1) NOT NULL DEFAULT '0',

	PRIMARY KEY (`plate`)
);

-- If the table already exists

ALTER TABLE `owned_vehicles` ADD change job VARCHAR(20) NOT NULL DEFAULT '';

Also, make all fields not null.
