### ISSUE TITLE
When i go to pound garage

### ISSUE THREAD

**Issue by nojus124** [HumanTree92/esx_advancedgarage#63]
When I go to pound garage. If I press's that spacer you don't have any cars in pounded garage. It does take money from me.

**Comment by HumanTree92** [comment]
Ah what? Can you please be more Descriptive.

**Comment by OZWorldTTV** [comment]
I have the same problem. Ok so if a cop/mechanic impounds my vehicle or my vehicle gets destroyed and I go to the garage it isn't there, then I go to the impound and I pay $1000 to get my car out there is no car at all in the list. Then if I disconnect then reconnect to the server and go to the impound the car is there for me to pull out. I've been trying to figure it out and I can't seem to wrap my head around it. I'm constantly giving people 1,000 back in game cash. This happens to everyone. Vanilla cars and Addon Cars. Anyway this can be fixed.

**Comment by HumanTree92** [comment]
You can simply fix it by going into the code and just setting it to not change the stored value. Sounds to me like the problem is probably lag. I've had a similar issue but it was due to lag, sometimes to many vehicles getting pulled out at the same time. If for example you had 30 people pull a car out at the same time or near each other it would cause problems.

**Comment by OZWorldTTV** [comment]
Where would I change that at? I'm still new to lua code.
